version: 2.1
orbs:
  codecov: codecov/codecov@1.1.0

executors:
  go_1_14_img:
    docker:
      - image: cimg/go:1.14

build-template: &build-template
  environment:
    TEST_RESULTS: /tmp/test-results # path to where test results will be saved

  steps:
    - checkout
    - run: mkdir -p $TEST_RESULTS # create the test results directory

    - restore_cache: # restores saved cache if no changes are detected since last run
        keys:
          - cimg-go-pkg-mod-{{ checksum "go.sum" }}

    - run:
        name: "Linter and Test Coverage Report"
        command: |
          make ci
          mv coverage.* $TEST_RESULTS/

    - save_cache:
        key: cimg-go-pkg-mod-{{ checksum "go.sum" }}
        paths:
          - "/home/circleci/go/pkg/mod"

    - store_artifacts:
        path: /tmp/test-results
        destination: truffls-go-test-output

    - store_test_results:
        path: /tmp/test-results

    - codecov/upload:
        file: /tmp/test-results/coverage.txt


jobs:
  go_1_14_job:
    executor: go_1_14_img
    <<: *build-template

workflows:
  version: 2
  build:
    jobs:
      - go_1_14_job
